"""add missing grievance columns and sla tracking

Revision ID: f22827d4345b
Revises: 6a4c2b0e8f9d
Create Date: 2026-04-19 23:53:33.178660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22827d4345b'
down_revision = '6a4c2b0e8f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_breached_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_column('sla_breached_at')

    # ### end Alembic commands ###
